export const UPDATE_PRICESLIST = 'UPDATE_PRICESLIST'
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS'
export const UPDATE_PRODUCTS2 = 'UPDATE_PRODUCTS2'
export const UPDATE_CARTLIST = 'UPDATE_CARTLIST'
export const ADD_TO_CART = 'ADD_TO_CART'
export const CACULATE_CART_PRICE = 'CACULATE_CART_PRICE'

export const INCREATEMENT_CART_ITEM_QUANTITY = 'INCREATEMENT_CART_ITEM_QUANTITY'
export const DECREATEMENT_CART_ITEM_QUANTITY = 'DECREATEMENT_CART_ITEM_QUANTITY'

export const UPDATE_CURRENT_DETAIL_CART = 'UPDATE_CURRENT_DETAIL_CART'
export const UPDATE_FAVORITE_LIST = 'UPDATE_FAVORITE_LIST'

export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'
export const ADD_TO_ORDER_HISTORY_LIST_FROM_CART = 'ADD_TO_ORDER_HISTORY_LIST_FROM_CART'